# These are supported funding model platforms

github: [Vaporjawn, Vapor-jawn, Vaporjawn-Mods]
custom: [https://www.venmo.com/Vaporjawn, https://www.paypal.me/Vaporjawn, https://cash.app/$vaporjawn]
ko_fi: vaporjawn
issuehunt: vaporjawn
